export const FETCH_STAR_WARS_PEOPLE_REQUEST = 'FETCH_STAR_WARS_PEOPLE_REQUEST';
export const FETCH_STAR_WARS_PEOPLE_SUCCESS = 'FETCH_STAR_WARS_PEOPLE_SUCCESS';
export const FETCH_STAR_WARS_PLANETS_REQUEST =
  'FETCH_STAR_WARS_PLANETS_REQUEST';
export const FETCH_STAR_WARS_PLANETS_SUCCESS =
  'FETCH_STAR_WARS_PLANETS_SUCCESS';
export const CONFIRMATION = 'CONFIRMATION';
